version: '3.8'

services:
  database:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./certify_init.sql:/docker-entrypoint-initdb.d/certify_init.sql
    networks:
      - network
    ports:
      - "5433:5432"

  certify:
    image: mosipid/inji-certify-with-plugins:0.12.2
    user: root
    ports:
      - 8090:8090
    environment:
      - container_user=mosip
      - active_profile_env=default,csvdp-drivinglicense
      - SPRING_CONFIG_NAME=certify
      - SPRING_CONFIG_LOCATION=/home/mosip/config/
      - enable_certify_artifactory=false
      - download_hsm_client=false
      - mosip_certify_domain_url=http://certify-nginx:80
    volumes:
      - ./config/certify-default.properties:/home/mosip/config/certify-default.properties
      - ./config/certify-csvdp-drivinglicense.properties:/home/mosip/config/certify-csvdp-drivinglicense.properties
      - ./data/CERTIFY_PKCS12:/home/mosip/CERTIFY_PKCS12
      # This can be disabled if one uses plugins included in inji-certify-with-plugins docker image.
      # - ./loader_path/certify/:/home/mosip/additional_jars/
      # modify the below file to change the identity fields in the VC
      - ./config/driving_license_data.csv:/home/mosip/config/driving_license_data.csv
    networks:
      - network
    depends_on:
      - database

  certify-nginx:
    image: nginx:stable
    ports:
      - 8091:80
    volumes:
      - ./certify-nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
    depends_on:
      - certify

networks:
  network:
    name: mosip_network
    external: true
